FROM python:3.8

RUN pip install \
        mlflow \
        boto3 \
        gcsfs \
        psycopg2-binary

COPY src/k8s/tracking_entrypoint.sh /tracking_entrypoint.sh

ENTRYPOINT [ "/bin/bash", "/tracking_entrypoint.sh" ]
