FROM python:3.7

RUN pip install mlflow \
    && pip install boto3 \
    && pip install psycopg2-binary

COPY src/k8s/tracking_entrypoint.sh /tracking_entrypoint.sh

ENTRYPOINT ["/bin/bash", "/tracking_entrypoint.sh"]
