apiVersion: batch/v1
kind: Job
metadata:
  name: "{replaced with MLflow Project name}"
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: "{replaced with MLflow Project name}"
        image: "{replaced with URI of Docker image created during Project execution}"
        command: ["{replaced with MLflow Project entry point command}"]
        env:
        - name: KUBE_MLFLOW_TRACKING_URI
          value: "postgresql://mlflow_user:mlflow@mlflow-postgres:31821/mlflow_db"
      resources:
        limits:
          nvidia.com/gpu: 1
          memory: 512Mi
        requests:
          memory: 256Mi
      restartPolicy: Never
