#!/bin/bash

set -e

sudo -u ec2-user -i <<'EOF'

mkdir -p rapids_kernel
cd rapids_kernel

wget -q https://data.rapids.ai/conda-pack/rapidsai/rapids22.06_cuda11.5_py3.8.tar.gz
echo "wget completed"

tar -xzf *.gz
echo "unzip completed"

source /home/ec2-user/rapids_kernel/bin/activate
conda-unpack
echo "unpack completed"

# optionally install AutoGluon for AutoML GPU demo
# source /home/ec2-user/rapids_kernel/bin/activate && pip install --pre autogluon

python -m ipykernel install --user --name rapids-2206
echo "kernel install completed"
EOF
