#!/bin/bash

set -e

sudo -u ec2-user -i <<'EOF'

echo $('pwd')
conda remove --name amazonei_mxnet_p27 -y --all
conda remove --name amazonei_mxnet_p36 -y --all
conda remove --name amazonei_pytorch_latest_p36 -y --all
conda remove --name amazonei_tensorflow2_p27 -y --all
conda remove --name amazonei_tensorflow2_p36 -y --all
conda remove --name amazonei_tensorflow_p27 -y --all
conda remove --name amazonei_tensorflow_p36 -y --all

echo "remove completed"

mkdir -p rapids_kernel
cd rapids_kernel

wget -q https://rapidsai-data.s3.us-east-2.amazonaws.com/conda-pack/rapidsai/rapids0.18_cuda11.0_py3.8.tar.gz
echo "wget completed"

tar -xzf *.gz
echo "unzip completed"

source /home/ec2-user/rapids_kernel/bin/activate
conda-unpack 
echo "unpack completed"

#pip install --pre autogluon

python -m ipykernel install --user --name rapids-18
echo "kernel install completed"
EOF