#!/bin/bash

# RAPIDS Lifecycle script 
# follows SageMaker 'Lifecycle Configuration Best Practices'
# https://docs.aws.amazon.com/sagemaker/latest/dg/nbi-lifecycle-config-install.html

sudo -u ec2-user -i <<'EOF'

S3_STORAGE="https://sagemaker-rapids-hpo-us-east-1.s3.amazonaws.com/rapids_15_py37.tar.gz"
CONDA_ENV="rapids_15_py37"
TARBALL="$CONDA_ENV.tar.gz"
UNPACK_TO="$CONDA_ENV"

echo "downloading compressed & packed RAPIDS conda environment"
wget -q $S3_STORAGE
mkdir -p "$UNPACK_TO"
tar -xzf $TARBALL -C "$UNPACK_TO"

echo "conda-unpack RAPIDS conda environment"
source "$UNPACK_TO/bin/activate"
conda-unpack

echo "add/install RAPIDS environment as a new SageMaker kernel"
python -m ipykernel install --user --name $CONDA_ENV

source deactivate

EOF

# Installed kernelspec rapids_15_py37 in /home/ec2-user/.local/share/jupyter/kernels/rapids_15_py37